/*! @license Firebase v3.7.5
    Build: 3.7.5-rc.1
    Terms: https://firebase.google.com/terms/ */
var firebase = null; (function() { var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},l=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},n=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&
self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),p=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q=this||self,r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},u=function(a,b){function c(){}c.prototype=b.prototype;a.ia=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,h){for(var k=Array(arguments.length-2),f=2;f<arguments.length;f++)k[f-2]=arguments[f];return b.prototype[e].apply(d,k)}};var v=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}u(w,Error);w.prototype.name="CustomError";function x(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");w.call(this,c+a[d])}u(x,w);x.prototype.name="AssertionError";function z(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var h=d}else a&&(e+=": "+a,h=b);throw new x(""+e,h||[]);}
var A=function(a,b,c){a||z("",null,b,Array.prototype.slice.call(arguments,2))},da=function(a,b,c){a==null&&z("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b,c){if(typeof a!=="function"){var d=typeof a;d=d!="object"?d:a?Array.isArray(a)?"array":d:"null";z("Expected function but got %s: %s.",[d,a],b,Array.prototype.slice.call(arguments,2))}};var C=function(a,b){this.ba=100;this.X=a;this.da=b;this.H=0;this.G=null};C.prototype.get=function(){if(this.H>0){this.H--;var a=this.G;this.G=a.next;a.next=null}else a=this.X();return a};C.prototype.put=function(a){this.da(a);this.H<this.ba&&(this.H++,a.next=this.G,this.G=a)};function ea(a){q.setTimeout(function(){throw a;},0)};var D=function(){this.I=this.u=null};D.prototype.add=function(a,b){var c=fa.get();c.set(a,b);this.I?this.I.next=c:(A(!this.u),this.u=c);this.I=c};D.prototype.remove=function(){var a=null;this.u&&(a=this.u,this.u=this.u.next,this.u||(this.I=null),a.next=null);return a};var fa=new C(function(){return new E},function(a){return a.reset()}),E=function(){this.next=this.scope=this.fn=null};E.prototype.set=function(a,b){this.fn=a;this.scope=b;this.next=null};
E.prototype.reset=function(){this.next=this.scope=this.fn=null};var F=q.console&&q.console.createTask?q.console.createTask.bind(q.console):void 0,G=F?Symbol("consoleTask"):void 0;
function H(a,b){function c(){var f=p.apply(0,arguments),g=this;return k.run(function(){return a.call.apply(a,[g].concat(f instanceof Array?f:n(l(f))))})}b=b===void 0?"anonymous":b;if(G&&a[G])return a;var d=a,e,h=(e=ha)==null?void 0:e();a=function(){var f=p.apply(0,arguments),g,m=(g=ha)==null?void 0:g();if(h!==m)throw Error(b+" was scheduled in '"+h+"' but called in '"+m+"'.\nMake sure your test awaits all async calls.\n\nTIP: To help investigate, debug the test in Chrome and look at the async portion\nof the call stack to see what originally scheduled the callback.  Then, make the\ntest wait for the relevant asynchronous work to finish.");return d.call.apply(d,
[this].concat(f instanceof Array?f:n(l(f))))};if(!F)return a;var k=F(a.name||b);c[da(G)]=k;return c}var ha;var I,J=!1,ia=new D,K=function(a,b){a=H(a,"goog.async.run");I||ja();J||(I(),J=!0);ia.add(a,b)},ja=function(){var a=Promise.resolve(void 0);I=function(){a.then(ka)}};function ka(){for(var a;a=ia.remove();){try{a.fn.call(a.scope)}catch(b){ea(b)}fa.put(a)}J=!1};var L=function(){};var O=function(a,b){this.h=0;this.V=void 0;this.v=this.j=this.o=null;this.F=this.J=!1;if(a!=L)try{var c=this;a.call(b,function(d){M(c,2,d)},function(d){if(!(d instanceof N))try{if(d instanceof Error)throw d;throw Error("Promise rejected.");}catch(e){}M(c,3,d)})}catch(d){M(this,3,d)}},la=function(){this.next=this.context=this.A=this.m=this.child=null;this.B=!1};la.prototype.reset=function(){this.context=this.A=this.m=this.child=null;this.B=!1};
var ma=new C(function(){return new la},function(a){a.reset()}),na=function(a,b,c){var d=ma.get();d.m=a;d.A=b;d.context=c;return d},pa=function(a,b,c){oa(a,b,c,null)||K(r(b,a))};O.prototype.then=function(a,b,c){a!=null&&B(a,"opt_onFulfilled should be a function.");b!=null&&B(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return qa(this,v(typeof a==="function"?a:null),v(typeof b==="function"?b:null),c)};O.prototype.$goog_Thenable=!0;
var sa=function(a,b,c,d){b!=null&&B(b,"opt_onFulfilled should be a function.");c!=null&&B(c,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");ra(a,na(b||L,c||null,d))};O.prototype.finally=function(a){var b=this;a=v(a);return new O(function(c,d){sa(b,function(e){a();c(e)},function(e){a();d(e)})})};O.prototype.W=function(a,b){return qa(this,null,v(a),b)};O.prototype.catch=O.prototype.W;
O.prototype.cancel=function(a){if(this.h==0){var b=new N(a);K(function(){ta(this,b)},this)}};
var ta=function(a,b){if(a.h==0)if(a.o){var c=a.o;if(c.j){for(var d=0,e=null,h=null,k=c.j;k&&(k.B||(d++,k.child==a&&(e=k),!(e&&d>1)));k=k.next)e||(h=k);e&&(c.h==0&&d==1?ta(c,b):(h?(d=h,A(c.j),A(d!=null),d.next==c.v&&(c.v=d),d.next=d.next.next):ua(c),va(c,e,3,b)))}a.o=null}else M(a,3,b)},ra=function(a,b){a.j||a.h!=2&&a.h!=3||wa(a);A(b.m!=null);a.v?a.v.next=b:a.j=b;a.v=b},qa=function(a,b,c,d){b&&(b=H(b,"goog.Promise.then"));c&&(c=H(c,"goog.Promise.then"));var e=na(null,null,null);e.child=new O(function(h,
k){e.m=b?function(f){try{var g=b.call(d,f);h(g)}catch(m){k(m)}}:h;e.A=c?function(f){try{var g=c.call(d,f);g===void 0&&f instanceof N?k(f):h(g)}catch(m){k(m)}}:k});e.child.o=a;ra(a,e);return e.child};O.prototype.fa=function(a){A(this.h==1);this.h=0;M(this,2,a)};O.prototype.ga=function(a){A(this.h==1);this.h=0;M(this,3,a)};
var M=function(a,b,c){a.h==0&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.h=1,oa(c,a.fa,a.ga,a)||(a.V=c,a.h=b,a.o=null,wa(a),b!=3||c instanceof N||xa(a,c)))},oa=function(a,b,c,d){if(a instanceof O)return sa(a,b,c,d),!0;if(a)try{var e=!!a.$goog_Thenable}catch(k){e=!1}else e=!1;if(e)return a.then(b,c,d),!0;e=typeof a;if(e=="object"&&a!=null||e=="function")try{var h=a.then;if(typeof h==="function")return ya(a,h,b,c,d),!0}catch(k){return c.call(d,k),!0}return!1},ya=function(a,
b,c,d,e){var h=!1,k=function(g){h||(h=!0,c.call(e,g))},f=function(g){h||(h=!0,d.call(e,g))};try{b.call(a,k,f)}catch(g){f(g)}},wa=function(a){a.J||(a.J=!0,K(a.Y,a))},ua=function(a){var b=null;a.j&&(b=a.j,a.j=b.next,b.next=null);a.j||(a.v=null);b!=null&&A(b.m!=null);return b};O.prototype.Y=function(){for(var a;a=ua(this);)va(this,a,this.h,this.V);this.J=!1};
var va=function(a,b,c,d){if(c==3&&b.A&&!b.B)for(;a&&a.F;a=a.o)a.F=!1;if(b.child)b.child.o=null,za(b,c,d);else try{b.B?b.m.call(b.context):za(b,c,d)}catch(e){Aa.call(null,e)}ma.put(b)},za=function(a,b,c){b==2?a.m.call(a.context,c):a.A&&a.A.call(a.context,c)},xa=function(a,b){a.F=!0;K(function(){a.F&&Aa.call(null,b)})},Aa=ea,N=function(a){w.call(this,a)};u(N,w);N.prototype.name="cancel";O.all=function(a){return new O(function(b,c){var d=a.length,e=[];if(d)for(var h=function(m,t){d--;e[m]=t;d==0&&b(e)},k=function(m){c(m)},f,g=0;g<a.length;g++)f=a[g],pa(f,r(h,g),k);else b(e)})};O.resolve=function(a){if(a instanceof O)return a;var b=new O(L);M(b,2,a);return b};O.reject=function(a){return new O(function(b,c){c(a)})};O.prototype["catch"]=O.prototype.W;var P=O;typeof Promise!=="undefined"&&(P=Promise);function Q(a,b){if(!(b instanceof Object))return b;switch(b.constructor){case Date:return new Date(b.getTime());case Object:a===void 0&&(a={});break;case Array:a=[];break;default:return b}for(var c in b)b.hasOwnProperty(c)&&(a[c]=Q(a[c],b[c]));return a};var Ba=Error.captureStackTrace,S=function(a,b){this.code=a;this.message=b;if(Ba)Ba(this,R.prototype.create);else{var c=Error.apply(this,arguments);this.name="FirebaseError";Object.defineProperty(this,"stack",{get:function(){return c.stack}})}};S.prototype.constructor=S;S.prototype.name="FirebaseError";var R=function(a,b,c){this.service=a;this.ea=b;this.errors=c;this.pattern=/\{\$([^}]+)}/g};
R.prototype.create=function(a,b){b===void 0&&(b={});var c=this.errors[a];a=this.service+"/"+a;c=c===void 0?"Error":c.replace(this.pattern,function(e,h){e=b[h];return e!==void 0?e.toString():"<"+h+"?>"});c=this.ea+": "+c+" ("+a+").";c=new S(a,c);for(var d in b)b.hasOwnProperty(d)&&d.slice(-1)!=="_"&&(c[d]=b[d]);return c};var Ca=P;function Da(a,b){a=new T(a,b);return a.subscribe.bind(a)}var T=function(a,b){var c=this;this.i=[];this.U=0;this.task=Ca.resolve();this.D=!1;this.M=b;this.task.then(function(){a(c)}).catch(function(d){c.error(d)})};T.prototype.next=function(a){U(this,function(b){b.next(a)})};T.prototype.error=function(a){U(this,function(b){b.error(a)});this.close(a)};T.prototype.complete=function(){U(this,function(a){a.complete()});this.close()};
T.prototype.subscribe=function(a,b,c){var d=this;if(a===void 0&&b===void 0&&c===void 0)throw Error("Missing Observer.");var e=Ea(a)?a:{next:a,error:b,complete:c};e.next===void 0&&(e.next=V);e.error===void 0&&(e.error=V);e.complete===void 0&&(e.complete=V);a=this.ha.bind(this,this.i.length);this.D&&this.task.then(function(){try{d.R?e.error(d.R):e.complete()}catch(h){}});this.i.push(e);return a};
T.prototype.ha=function(a){this.i!==void 0&&this.i[a]!==void 0&&(delete this.i[a],--this.U,this.U===0&&this.M!==void 0&&this.M(this))};var U=function(a,b){if(!a.D)for(var c=0;c<a.i.length;c++)Fa(a,c,b)},Fa=function(a,b,c){a.task.then(function(){if(a.i!==void 0&&a.i[b]!==void 0)try{c(a.i[b])}catch(d){typeof console!=="undefined"&&console.error&&console.error(d)}})};T.prototype.close=function(a){var b=this;this.D||(this.D=!0,a!==void 0&&(this.R=a),this.task.then(function(){b.i=void 0;b.M=void 0}))};
function Ea(a){if(typeof a!=="object"||a===null)return!1;var b=l(["next","error","complete"]),c=b.next(),d;try{for(;!c.done;c=b.next()){var e=c.value;if(e in a&&typeof a[e]==="function")return!0}}finally{c&&!c.done&&(d=b.return)&&d.call(b)}return!1}function V(){};var W=P,X=function(a,b,c){var d=this;this.S=c;this.T=!1;this.l={};this.K=b;this.P=Q(void 0,a);a="serviceAccount"in this.P;("credential"in this.P||a)&&typeof console!=="undefined"&&console.log("The '"+(a?"serviceAccount":"credential")+"' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.");Object.keys(c.INTERNAL.factories).forEach(function(e){var h=
c.INTERNAL.useAsService(d,e);h!==null&&(h=d.aa.bind(d,h),d[e]=h)})};ca.Object.defineProperties(X.prototype,{name:{configurable:!0,enumerable:!0,get:function(){Y(this);return this.K}},options:{configurable:!0,enumerable:!0,get:function(){Y(this);return this.P}}});
X.prototype.delete=function(){var a=this;return(new W(function(b){Y(a);b()})).then(function(){a.S.INTERNAL.removeApp(a.K);var b=[];Object.keys(a.l).forEach(function(c){Object.keys(a.l[c]).forEach(function(d){b.push(a.l[c][d])})});return W.all(b.filter(function(c){return"INTERNAL"in c}).map(function(c){return c.INTERNAL.delete()}))}).then(function(){a.T=!0;a.l={}})};
X.prototype.aa=function(a,b){Y(this);typeof this.l[a]==="undefined"&&(this.l[a]={});var c=b||"[DEFAULT]";return typeof this.l[a][c]==="undefined"?(b=this.S.INTERNAL.factories[a](this,this.Z.bind(this),b),this.l[a][c]=b):this.l[a][c]};X.prototype.Z=function(a){Q(this,a)};var Y=function(a){a.T&&Z("app-deleted",{name:a.K})};X.prototype.name&&X.prototype.options||X.prototype.delete||console.log("dc");
function Ga(){function a(f){f=f||"[DEFAULT]";var g=d[f];g===void 0&&Z("no-app",{name:f});return g}function b(f,g){Object.keys(e).forEach(function(m){m=c(f,m);if(m!==null&&h[m])h[m](g,f)})}function c(f,g){if(g==="serverAuth")return null;var m=g;f=f.options;g==="auth"&&(f.serviceAccount||f.credential)&&(m="serverAuth","serverAuth"in e||Z("sa-not-supported"));return m}var d={},e={},h={},k={__esModule:!0,initializeApp:function(f,g){g===void 0?g="[DEFAULT]":(typeof g!=="string"||g==="")&&Z("bad-app-name",
{name:g+""});d[g]!==void 0&&Z("duplicate-app",{name:g});f=new X(f,g,k);d[g]=f;b(f,"create");f.INTERNAL!=void 0&&f.INTERNAL.getToken!=void 0||Q(f,{INTERNAL:{getUid:function(){return null},getToken:function(){return W.resolve(null)},addAuthTokenListener:function(){},removeAuthTokenListener:function(){}}});return f},app:a,apps:null,Promise:W,SDK_VERSION:"0.0.0",INTERNAL:{registerService:function(f,g,m,t,Ha){e[f]&&Z("duplicate-service",{name:f});e[f]=Ha?g:function(y,Ia){return g(y,Ia,"[DEFAULT]")};t&&
(h[f]=t);t=function(y){y===void 0&&(y=a());typeof y[f]!=="function"&&Z("invalid-app-argument",{name:f});return y[f]()};m!==void 0&&Q(t,m);return k[f]=t},createFirebaseNamespace:Ga,extendNamespace:function(f){Q(k,f)},createSubscribe:Da,ErrorFactory:R,removeApp:function(f){b(d[f],"delete");delete d[f]},factories:e,useAsService:c,Promise:O,deepExtend:Q}};k["default"]=k;Object.defineProperty(k,"apps",{get:function(){return Object.keys(d).map(function(f){return d[f]})}});a.App=X;return k}
function Z(a,b){throw Ja.create(a,b);}
var Ja=new R("app","Firebase",{"no-app":"No Firebase App '{$name}' has been created - call Firebase App.initializeApp()","bad-app-name":"Illegal App name: '{$name}","duplicate-app":"Firebase App named '{$name}' already exists","app-deleted":"Firebase App named '{$name}' already deleted","duplicate-service":"Firebase service named '{$name}' already registered","sa-not-supported":"Initializing the Firebase SDK with a service account is only allowed in a Node.js environment. On client devices, you should instead initialize the SDK with an api key and auth domain","invalid-app-argument":"firebase.{$name}() takes either no argument or a Firebase App instance."});typeof firebase!=="undefined"&&(firebase=Ga()); }).call(this);
firebase.SDK_VERSION = "3.7.5";
'use strict';var n,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var da;
if(typeof Object.setPrototypeOf=="function")da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.M=b.prototype}function ka(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function u(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ka(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function la(a){return ma(a,a)}function ma(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var na=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)w(d,e)&&(a[e]=d[e])}return a};r("Object.assign",function(a){return a||na});function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}r("globalThis",function(a){return a||p});
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.h=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(ka(this))}});return a});function pa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(g){this.h=0;this.j=void 0;this.i=[];this.o=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.h=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.i=function(g){if(this.h==null){this.h=[];var h=this;this.j(function(){h.m()})}this.h.push(g)};var e=p.setTimeout;c.prototype.j=function(g){e(g,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.l(l)}}}this.h=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.D),reject:g(this.m)}};b.prototype.D=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.F(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.C(g):this.u(g)}};
b.prototype.C=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.H(h,g):this.u(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.u=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.j=h;this.h===2&&this.I();this.A()};b.prototype.I=function(){var g=this;e(function(){if(g.B()){var h=p.console;typeof h!=="undefined"&&h.error(g.j)}},1)};b.prototype.B=
function(){if(this.o)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return k(g)};b.prototype.A=function(){if(this.i!=null){for(var g=0;g<this.i.length;++g)f.i(this.i[g]);this.i=null}};var f=new c;b.prototype.F=
function(g){var h=this.l();g.O(h.resolve,h.reject)};b.prototype.H=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(q,t){return typeof q=="function"?function(y){try{l(q(y))}catch(E){m(E)}}:t}var l,m,v=new b(function(q,t){l=q;m=t});this.O(k(g,l),k(h,m));return v};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.O=function(g,h){function k(){switch(l.h){case 1:g(l.j);break;case 2:h(l.j);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.i==null?f.i(k):this.i.push(k);this.o=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=u(g),m=l.next();!m.done;m=l.next())d(m.value).O(h,k)})};b.all=function(g){var h=u(g),k=h.next();return k.done?d([]):new b(function(l,m){function v(y){return function(E){q[y]=E;t--;t==0&&l(q)}}var q=[],t=0;do q.push(void 0),t++,d(k.value).O(v(q.length-1),m),k=h.next();while(!k.done)})};return b});
r("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
r("WeakMap",function(a){function b(k){this.h=(h+=Math.random()+1).toString();if(k){k=u(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!w(k,g)){var l=new c;ba(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(v){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!w(k,g))throw Error("WeakMap key fail: "+k);k[g][this.h]=l;return this};b.prototype.get=function(k){return d(k)&&w(k,g)?k[g][this.h]:void 0};b.prototype.has=function(k){return d(k)&&w(k,
g)&&w(k[g],this.h)};b.prototype.delete=function(k){return d(k)&&w(k,g)&&w(k[g],this.h)?delete k[g][this.h]:!1};return b});
r("Map",function(a){function b(){var h={};return h.G=h.next=h.head=h}function c(h,k){var l=h[1];return pa(function(){if(l){for(;l.head!=h[1];)l=l.G;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&w(h[0],l))for(h=0;h<m.length;h++){var v=m[h];if(k!==k&&v.key!==v.key||k===v.key)return{id:l,list:m,index:h,entry:v}}return{id:l,
list:m,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=u(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(u([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(v){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],G:this[1].G,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].G.next=l.entry,this[1].G=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.entry.G.next=h.entry.next,
h.entry.next.G=h.entry.G,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].G=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=
function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.entries",function(a){return a?a:function(){return qa(this,function(b,c){return[b,c]})}});
r("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}});
r("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ra=ra||{},x=this||self;function sa(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function z(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function ta(a,b,c){return a.call.apply(a.bind,arguments)}
function ua(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ta:ua;return A.apply(null,arguments)}
function B(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qa=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};function C(a,b,c){this.code="auth/"+a;this.message=b||va[a]||"";this.h=c||null}B(C,Error);C.prototype.toJSON=function(){var a={code:this.code,message:this.message};this.h&&(a.serverResponse=this.h);return a};
var va={"api-key-service-blocked":"The request is denied because it violates [API key HTTP restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_http_restrictions).","admin-restricted-operation":"This operation is restricted to administrators only.","argument-error":"","app-not-authorized":"This app, identified by the domain where it's hosted, is not authorized to use Firebase Authentication with the provided API key. Review your key configuration in the Google API console.","app-not-installed":"The requested mobile application corresponding to the identifier (Android package name or iOS bundle ID) provided is not installed on this device.",
"bad-request":"The requested action is invalid.","captcha-check-failed":"The reCAPTCHA response token provided is either invalid, expired, already used or the domain associated with it does not match the list of whitelisted domains.","code-expired":"The SMS code has expired. Please re-send the verification code to try again.","cordova-not-ready":"Cordova framework is not ready.","cors-unsupported":"This browser is not supported.","credential-already-in-use":"This credential is already associated with a different user account.",
"custom-token-mismatch":"The custom token corresponds to a different audience.","requires-recent-login":"This operation is sensitive and requires recent authentication. Log in again before retrying this request.","dynamic-link-not-activated":"Please activate Dynamic Links in the Firebase Console and agree to the terms and conditions.","email-change-needs-verification":"Multi-factor users must always have a verified email.","email-already-in-use":"The email address is already in use by another account.",
"expired-action-code":"The action code has expired. ","cancelled-popup-request":"This operation has been cancelled due to another conflicting popup being opened.","internal-error":"An internal error has occurred.","invalid-app-credential":"The phone verification request contains an invalid application verifier. The reCAPTCHA token response is either invalid or expired.","invalid-app-id":"The mobile app identifier is not registed for the current project.","invalid-user-token":"This user's credential isn't valid for this project. This can happen if the user's token has been tampered with, or if the user isn't for the project associated with this API key.",
"invalid-auth-event":"An internal error has occurred.","invalid-verification-code":"The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure to use the verification code provided by the user.","invalid-continue-uri":"The continue URL provided in the request is invalid.","invalid-cordova-configuration":"The following Cordova plugins must be installed to enable OAuth sign-in: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser and cordova-plugin-customurlscheme.",
"invalid-custom-token":"The custom token format is incorrect. Please check the documentation.","invalid-dynamic-link-domain":"The provided dynamic link domain is not configured or authorized for the current project.","invalid-email":"The email address is badly formatted.","invalid-api-key":"Your API key is invalid, please check you have copied it correctly.","invalid-cert-hash":"The SHA-1 certificate hash provided is invalid.","invalid-credential":"The supplied auth credential is malformed or has expired.",
"invalid-message-payload":"The email template corresponding to this action contains invalid characters in its message. Please fix by going to the Auth email templates section in the Firebase Console.","invalid-multi-factor-session":"The request does not contain a valid proof of first factor successful sign-in.","invalid-oauth-provider":"EmailAuthProvider is not supported for this operation. This operation only supports OAuth providers.","invalid-oauth-client-id":"The OAuth client ID provided is either invalid or does not match the specified API key.",
"unauthorized-domain":"This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.","invalid-action-code":"The action code is invalid. This can happen if the code is malformed, expired, or has already been used.","wrong-password":"The password is invalid or the user does not have a password.","invalid-persistence-type":"The specified persistence type is invalid. It can only be local, session or none.","invalid-phone-number":"The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].",
"invalid-provider-id":"The specified provider ID is invalid.","invalid-recipient-email":"The email corresponding to this action failed to send as the provided recipient email address is invalid.","invalid-sender":"The email template corresponding to this action contains an invalid sender email or name. Please fix by going to the Auth email templates section in the Firebase Console.","invalid-verification-id":"The verification ID used to create the phone auth credential is invalid.","invalid-tenant-id":"The Auth instance's tenant ID is invalid.",
"multi-factor-info-not-found":"The user does not have a second factor matching the identifier provided.","multi-factor-auth-required":"Proof of ownership of a second factor is required to complete sign-in.","missing-android-pkg-name":"An Android Package Name must be provided if the Android App is required to be installed.","auth-domain-config-required":"Be sure to include authDomain when calling firebase.initializeApp(), by following the instructions in the Firebase console.","missing-app-credential":"The phone verification request is missing an application verifier assertion. A reCAPTCHA response token needs to be provided.",
"missing-verification-code":"The phone auth credential was created with an empty SMS verification code.","missing-continue-uri":"A continue URL must be provided in the request.","missing-iframe-start":"An internal error has occurred.","missing-ios-bundle-id":"An iOS Bundle ID must be provided if an App Store ID is provided.","missing-multi-factor-info":"No second factor identifier is provided.","missing-multi-factor-session":"The request is missing proof of first factor successful sign-in.","missing-or-invalid-nonce":"The request does not contain a valid nonce. This can occur if the SHA-256 hash of the provided raw nonce does not match the hashed nonce in the ID token payload.",
"missing-phone-number":"To send verification codes, provide a phone number for the recipient.","missing-verification-id":"The phone auth credential was created with an empty verification ID.","app-deleted":"This instance of FirebaseApp has been deleted.","account-exists-with-different-credential":"An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.","network-request-failed":"A network error (such as timeout, interrupted connection or unreachable host) has occurred.",
"no-auth-event":"An internal error has occurred.","no-such-provider":"User was not linked to an account with the given provider.","null-user":"A null user object was provided as the argument for an operation which requires a non-null user object.","operation-not-allowed":"The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.","operation-not-supported-in-this-environment":'This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.',
"password-does-not-meet-requirements":"The provided password does not meet the configured requirements.","popup-blocked":"Unable to establish a connection with the popup. It may have been blocked by the browser.","popup-closed-by-user":"The popup has been closed by the user before finalizing the operation.","provider-already-linked":"User can only be linked to one identity for the given provider.","quota-exceeded":"The project's quota for this operation has been exceeded.","redirect-cancelled-by-user":"The redirect operation has been cancelled by the user before finalizing.",
"redirect-operation-pending":"A redirect sign-in operation is already pending.","rejected-credential":"The request contains malformed or mismatching credentials.","second-factor-already-in-use":"The second factor is already enrolled on this account.","maximum-second-factor-count-exceeded":"The maximum allowed number of second factors on a user has been exceeded.","tenant-id-mismatch":"The provided tenant ID does not match the Auth instance's tenant ID",timeout:"The operation has timed out.","user-token-expired":"The user's credential is no longer valid. The user must sign in again.",
"too-many-requests":"We have blocked all requests from this device due to unusual activity. Try again later.","unauthorized-continue-uri":"The domain of the continue URL is not whitelisted.  Please whitelist the domain in the Firebase console.","unsupported-first-factor":"Enrolling a second factor or signing in with a multi-factor account requires sign-in with a supported first factor.","unsupported-persistence-type":"The current environment does not support the specified persistence type.","unsupported-tenant-operation":"This operation is not supported in a multi-tenant context.",
"unverified-email":"The operation requires a verified email.","user-cancelled":"The user did not grant your application the permissions it requested.","user-not-found":"There is no user record corresponding to this identifier. The user may have been deleted.","user-disabled":"The user account has been disabled by an administrator.","user-mismatch":"The supplied credentials do not correspond to the previously signed in user.","user-signed-out":"","weak-password":"The password must be 6 characters long or more.",
"web-storage-unsupported":"This browser is not supported or 3rd party cookies and data may be disabled."};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}B(D,Error);D.prototype.name="CustomError";var wa;var xa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},za=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function Aa(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ba(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Ca="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Da(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ca.length;f++)c=Ca[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function F(a,b){return a.indexOf(b)!=-1};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Ea=globalThis.trustedTypes,Fa;function Ga(){var a=null;if(!Ea)return a;try{var b=function(c){return c};a=Ea.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function Ha(){Fa===void 0&&(Fa=Ga());return Fa};function Ia(a){this.h=a}Ia.prototype.toString=function(){return this.h+""};function Ja(a){var b=Ha();a=b?b.createScriptURL(a):a;return new Ia(a)}function Ka(a){if(a instanceof Ia)return a.h;throw Error("");};function G(a){this.h=a}G.prototype.toString=function(){return this.h};var La=new G("about:invalid#zClosurez");function Ma(a){this.la=a}function H(a){return new Ma(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Na=[H("data"),H("http"),H("https"),H("mailto"),H("ftp"),new Ma(function(a){return/^[^:]*([/?#]|$)/.test(a)})];function I(a){this.h=a}I.prototype.toString=function(){return this.h+""};function Oa(a){var b=Ha();a=b?b.createHTML(a):a;return new I(a)}function Pa(a){if(a instanceof I)return a.h;throw Error("");};function Qa(a,b){b=b===void 0?document:b;var c,d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,a+"[nonce]");return b==null?"":b.nonce||b.getAttribute("nonce")||""};function Ra(a,b){a.src=Ka(b);(b=Qa("script",a.ownerDocument))&&a.setAttribute("nonce",b)};function Sa(a){this.h=a}Sa.prototype.toString=function(){return this.h};function Ta(a){if(a instanceof Sa)return a.h;throw Error("");};var Ua,Va;a:{for(var Wa=["CLOSURE_FLAGS"],Xa=x,Ya=0;Ya<Wa.length;Ya++)if(Xa=Xa[Wa[Ya]],Xa==null){Va=null;break a}Va=Xa}var Za=Va&&Va[610401301];Ua=Za!=null?Za:!1;function $a(){var a=x.navigator;return a&&(a=a.userAgent)?a:""}var ab,bb=x.navigator;ab=bb?bb.userAgentData||null:null;function J(a){return F($a(),a)};var cb=Ua&&ab&&ab.brands.length>0?!1:J("Opera"),db=Ua&&ab&&ab.brands.length>0?!1:J("Trident")||J("MSIE"),eb=J("Edge"),fb=J("Gecko")&&!(F($a().toLowerCase(),"webkit")&&!J("Edge"))&&!(J("Trident")||J("MSIE"))&&!J("Edge"),gb=F($a().toLowerCase(),"webkit")&&!J("Edge");function hb(){var a=x.document;return a?a.documentMode:void 0}var ib;
a:{var jb="",kb=function(){var a=$a();if(fb)return/rv:([^\);]+)(\)|;)/.exec(a);if(eb)return/Edge\/([\d\.]+)/.exec(a);if(db)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gb)return/WebKit\/(\S+)/.exec(a);if(cb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kb&&(jb=kb?kb[1]:"");if(db){var lb=hb();if(lb!=null&&lb>parseFloat(jb)){ib=String(lb);break a}}ib=jb}var mb=ib,nb;if(x.document&&db){var ob=hb();nb=ob?ob:parseInt(mb,10)||void 0}else nb=void 0;var pb=nb;function qb(a){return a instanceof I?a:Oa(String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"))};function rb(a){var b=oa.apply(1,arguments);if(b.length===0)return Ja(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Ja(c)};function sb(a,b){Ba(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:tb.hasOwnProperty(d)?a.setAttribute(tb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var tb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function ub(a,b,c){function d(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var f=c[e];if(!sa(f)||z(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(z(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}ya(g?Aa(f):f,d)}}}function vb(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function wb(a){this.h=a||x.document||document}function xb(a,b){a=a.h;return(b=b&&b!="*"?String(b).toUpperCase():"")?a.querySelectorAll(b):a.getElementsByTagName("*")}wb.prototype.i=function(a,b,c){var d=this.h,e=arguments,f=e[1],g=vb(d,String(e[0]));f&&(typeof f==="string"?g.className=f:Array.isArray(f)?g.className=f.join(" "):sb(g,f));e.length>2&&ub(d,g,e);return g};function yb(a,b){return vb(a.h,b)}wb.prototype.j=function(a,b){a.appendChild(b)};function K(){this.u=this.u;this.A=this.A}K.prototype.u=!1;K.prototype.isDisposed=function(){return this.u};K.prototype.dispose=function(){this.u||(this.u=!0,this.K())};K.prototype[Symbol.dispose]=function(){this.dispose()};K.prototype.K=function(){if(this.A)for(;this.A.length;)this.A.shift()()};function L(a,b){this.type=a;this.h=this.target=b;this.defaultPrevented=!1}L.prototype.i=function(){this.defaultPrevented=!0};var zb=function(){if(!x.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};x.addEventListener("test",c,b);x.removeEventListener("test",c,b)}catch(d){}return a}();function M(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.h=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.j=null;a&&this.init(a,b)}B(M,L);
M.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.h=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.j=a;a.defaultPrevented&&M.M.i.call(this)};M.prototype.i=function(){M.M.i.call(this);var a=this.j;a.preventDefault?a.preventDefault():a.returnValue=!1};var Ab="closure_listenable_"+(Math.random()*1E6|0);var Bb=0;function Cb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.handler=e;this.key=++Bb;this.L=this.N=!1}function Db(a){a.L=!0;a.listener=null;a.proxy=null;a.src=null;a.handler=null};function Eb(a){this.src=a;this.h={};this.i=0}Eb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.h[f];a||(a=this.h[f]=[],this.i++);var g=Fb(a,b,d,e);g>-1?(b=a[g],c||(b.N=!1)):(b=new Cb(b,this.src,f,!!d,e),b.N=c,a.push(b));return b};function Gb(a,b){var c=b.type;if(c in a.h){var d=a.h[c],e=xa(d,b),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(Db(b),a.h[c].length==0&&(delete a.h[c],a.i--))}}
function Fb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.L&&f.listener==b&&f.capture==!!c&&f.handler==d)return e}return-1};var Hb="closure_lm_"+(Math.random()*1E6|0),Ib={},Jb=0;function Kb(a,b,c,d,e){if(d&&d.once)Lb(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Kb(a,b[f],c,d,e);else c=Mb(c),a&&a[Ab]?Nb(a,b,c,z(d)?!!d.capture:!!d,e):Ob(a,b,c,!1,d,e)}
function Ob(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=z(e)?!!e.capture:!!e,h=Pb(a);h||(a[Hb]=h=new Eb(a));c=h.add(b,c,d,g,f);if(!c.proxy){d=Qb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)zb||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Rb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Jb++}}
function Qb(){function a(c){return b.call(a.src,a.listener,c)}var b=Sb;return a}function Lb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Lb(a,b[f],c,d,e);else c=Mb(c),a&&a[Ab]?Tb(a,b,c,z(d)?!!d.capture:!!d,e):Ob(a,b,c,!0,d,e)}
function Ub(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ub(a,b[f],c,d,e);else(d=z(d)?!!d.capture:!!d,c=Mb(c),a&&a[Ab])?(a=a.j,b=String(b).toString(),b in a.h&&(f=a.h[b],c=Fb(f,c,d,e),c>-1&&(Db(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.h[b],a.i--)))):a&&(a=Pb(a))&&(b=a.h[b.toString()],a=-1,b&&(a=Fb(b,c,d,e)),(c=a>-1?b[a]:null)&&Vb(c))}
function Vb(a){if(typeof a!=="number"&&a&&!a.L){var b=a.src;if(b&&b[Ab])Gb(b.j,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Rb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Jb--;(c=Pb(b))?(Gb(c,a),c.i==0&&(c.src=null,b[Hb]=null)):Db(a)}}}function Rb(a){return a in Ib?Ib[a]:Ib[a]="on"+a}function Sb(a,b){if(a.L)a=!0;else{b=new M(b,this);var c=a.listener,d=a.handler||a.src;a.N&&Vb(a);a=c.call(d,b)}return a}
function Pb(a){a=a[Hb];return a instanceof Eb?a:null}var Wb="__closure_events_fn_"+(Math.random()*1E9>>>0);function Mb(a){if(typeof a==="function")return a;a[Wb]||(a[Wb]=function(b){return a.handleEvent(b)});return a[Wb]};var N=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function Xb(a,b){this.j=a;this.l=b;this.i=0;this.h=null}Xb.prototype.get=function(){if(this.i>0){this.i--;var a=this.h;this.h=a.next;a.next=null}else a=this.j();return a};function Yb(a,b){a.l(b);a.i<100&&(a.i++,b.next=a.h,a.h=b)};function Zb(a){x.setTimeout(function(){throw a;},0)};function $b(){this.i=this.h=null}$b.prototype.add=function(a,b){var c=ac.get();c.set(a,b);this.i?this.i.next=c:this.h=c;this.i=c};function bc(){var a=cc,b=null;a.h&&(b=a.h,a.h=a.h.next,a.h||(a.i=null),b.next=null);return b}var ac=new Xb(function(){return new dc},function(a){return a.reset()});function dc(){this.next=this.scope=this.h=null}dc.prototype.set=function(a,b){this.h=a;this.scope=b;this.next=null};dc.prototype.reset=function(){this.next=this.scope=this.h=null};var ec,fc=!1,cc=new $b;function hc(a,b){ec||ic();fc||(ec(),fc=!0);cc.add(a,b)}function ic(){var a=Promise.resolve(void 0);ec=function(){a.then(jc)}}function jc(){for(var a;a=bc();){try{a.h.call(a.scope)}catch(b){Zb(b)}Yb(ac,a)}fc=!1};function kc(){};function lc(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function O(a){this.h=0;this.o=void 0;this.l=this.i=this.j=null;this.m=this.u=!1;if(a!=kc)try{var b=this;a.call(void 0,function(c){P(b,2,c)},function(c){P(b,3,c)})}catch(c){P(this,3,c)}}function mc(){this.next=this.j=this.i=this.l=this.h=null;this.m=!1}mc.prototype.reset=function(){this.j=this.i=this.l=this.h=null;this.m=!1};var nc=new Xb(function(){return new mc},function(a){a.reset()});function oc(a,b,c){var d=nc.get();d.l=a;d.i=b;d.j=c;return d}
function Q(a){if(a instanceof O)return a;var b=new O(kc);P(b,2,a);return b}function pc(){var a=new C("internal-error");return new O(function(b,c){c(a)})}O.prototype.then=function(a,b,c){return qc(this,N(typeof a==="function"?a:null),N(typeof b==="function"?b:null),c)};O.prototype.$goog_Thenable=!0;function rc(a,b){return qc(a,null,N(b))}O.prototype.cancel=function(a){if(this.h==0){var b=new sc(a);hc(function(){tc(this,b)},this)}};
function tc(a,b){if(a.h==0)if(a.j){var c=a.j;if(c.i){for(var d=0,e=null,f=null,g=c.i;g&&(g.m||(d++,g.h==a&&(e=g),!(e&&d>1)));g=g.next)e||(f=g);e&&(c.h==0&&d==1?tc(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):uc(c),vc(c,e,3,b)))}a.j=null}else P(a,3,b)}function wc(a,b){a.i||a.h!=2&&a.h!=3||xc(a);a.l?a.l.next=b:a.i=b;a.l=b}
function qc(a,b,c,d){var e=oc(null,null,null);e.h=new O(function(f,g){e.l=b?function(h){try{var k=b.call(d,h);f(k)}catch(l){g(l)}}:f;e.i=c?function(h){try{var k=c.call(d,h);k===void 0&&h instanceof sc?g(h):f(k)}catch(l){g(l)}}:g});e.h.j=a;wc(a,e);return e.h}O.prototype.A=function(a){this.h=0;P(this,2,a)};O.prototype.B=function(a){this.h=0;P(this,3,a)};
function P(a,b,c){if(a.h==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.h=1;a:{var d=c,e=a.A,f=a.B;if(d instanceof O){wc(d,oc(e||kc,f||null,a));var g=!0}else if(lc(d))d.then(e,f,a),g=!0;else{if(z(d))try{var h=d.then;if(typeof h==="function"){yc(d,h,e,f,a);g=!0;break a}}catch(k){f.call(a,k);g=!0;break a}g=!1}}g||(a.o=c,a.h=b,a.j=null,xc(a),b!=3||c instanceof sc||zc(a,c))}}
function yc(a,b,c,d,e){function f(k){h||(h=!0,d.call(e,k))}function g(k){h||(h=!0,c.call(e,k))}var h=!1;try{b.call(a,g,f)}catch(k){f(k)}}function xc(a){a.u||(a.u=!0,hc(a.v,a))}function uc(a){var b=null;a.i&&(b=a.i,a.i=b.next,b.next=null);a.i||(a.l=null);return b}O.prototype.v=function(){for(var a;a=uc(this);)vc(this,a,this.h,this.o);this.u=!1};
function vc(a,b,c,d){if(c==3&&b.i&&!b.m)for(;a&&a.m;a=a.j)a.m=!1;if(b.h)b.h.j=null,Ac(b,c,d);else try{b.m?b.l.call(b.j):Ac(b,c,d)}catch(e){Bc.call(null,e)}Yb(nc,b)}function Ac(a,b,c){b==2?a.l.call(a.j,c):a.i&&a.i.call(a.j,c)}function zc(a,b){a.m=!0;hc(function(){a.m&&Bc.call(null,b)})}var Bc=Zb;function sc(a){D.call(this,a)}B(sc,D);sc.prototype.name="cancel";function R(){K.call(this);this.j=new Eb(this);this.ba=this;this.I=null}B(R,K);R.prototype[Ab]=!0;R.prototype.addEventListener=function(a,b,c,d){Kb(this,a,b,c,d)};R.prototype.removeEventListener=function(a,b,c,d){Ub(this,a,b,c,d)};
R.prototype.dispatchEvent=function(a){var b,c=this.I;if(c)for(b=[];c;c=c.I)b.push(c);c=this.ba;var d=a.type||a;if(typeof a==="string")a=new L(a,c);else if(a instanceof L)a.target=a.target||c;else{var e=a;a=new L(d,c);Da(a,e)}e=!0;var f;if(b)for(f=b.length-1;f>=0;f--){var g=a.h=b[f];e=Cc(g,d,!0,a)&&e}g=a.h=c;e=Cc(g,d,!0,a)&&e;e=Cc(g,d,!1,a)&&e;if(b)for(f=0;f<b.length;f++)g=a.h=b[f],e=Cc(g,d,!1,a)&&e;return e};
R.prototype.K=function(){R.M.K.call(this);if(this.j){var a=this.j,b=0,c;for(c in a.h){for(var d=a.h[c],e=0;e<d.length;e++)++b,Db(d[e]);delete a.h[c];a.i--}}this.I=null};function Nb(a,b,c,d,e){a.j.add(String(b),c,!1,d,e)}function Tb(a,b,c,d,e){a.j.add(String(b),c,!0,d,e)}
function Cc(a,b,c,d){b=a.j.h[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.L&&g.capture==c){var h=g.listener,k=g.handler||g.src;g.N&&Gb(a.j,g);e=h.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};var Dc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ec(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function S(a){this.h=this.o=this.j="";this.v=null;this.u=this.l="";this.m=!1;var b;a instanceof S?(this.m=a.m,Fc(this,a.j),this.o=a.o,this.h=a.h,Gc(this,a.v),this.l=a.l,Hc(this,Ic(a.i)),this.u=a.u):a&&(b=String(a).match(Dc))?(this.m=!1,Fc(this,b[1]||"",!0),this.o=Jc(b[2]||""),this.h=Jc(b[3]||"",!0),Gc(this,b[4]),this.l=Jc(b[5]||"",!0),Hc(this,b[6]||"",!0),this.u=Jc(b[7]||"")):(this.m=!1,this.i=new Kc(null,this.m))}
S.prototype.toString=function(){var a=[],b=this.j;b&&a.push(Lc(b,Mc,!0),":");var c=this.h;if(c||b=="file")a.push("//"),(b=this.o)&&a.push(Lc(b,Mc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.v,c!=null&&a.push(":",String(c));if(c=this.l)this.h&&c.charAt(0)!="/"&&a.push("/"),a.push(Lc(c,c.charAt(0)=="/"?Nc:Oc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.u)&&a.push("#",Lc(c,Pc));return a.join("")};
S.prototype.resolve=function(a){var b=new S(this),c=!!a.j;c?Fc(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.h;c?b.h=a.h:c=a.v!=null;var d=a.l;if(c)Gc(b,a.v);else if(c=!!a.l){if(d.charAt(0)!="/")if(this.h&&!this.l)d="/"+d;else{var e=b.l.lastIndexOf("/");e!=-1&&(d=b.l.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(F(e,"./")||F(e,"/.")){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];h=="."?d&&g==e.length&&f.push(""):h==".."?((f.length>1||f.length==1&&f[0]!="")&&f.pop(),d&&
g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.l=d:c=a.i.toString()!=="";c?Hc(b,Ic(a.i)):c=!!a.u;c&&(b.u=a.u);return b};function Fc(a,b,c){a.j=c?Jc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Gc(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.v=b}else a.v=null}function Hc(a,b,c){b instanceof Kc?(a.i=b,Qc(a.i,a.m)):(c||(b=Lc(b,Rc)),a.i=new Kc(b,a.m))}function Sc(a,b){return a.i.get(b)}function T(a){return a instanceof S?new S(a):new S(a)}
function Jc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Lc(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Tc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Tc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Mc=/[#\/\?@]/g,Oc=/[#\?:]/g,Nc=/[#\?]/g,Rc=/[#\?@]/g,Pc=/#/g;function Kc(a,b){this.i=this.h=null;this.j=a||null;this.l=!!b}
function U(a){a.h||(a.h=new Map,a.i=0,a.j&&Ec(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}n=Kc.prototype;n.add=function(a,b){U(this);this.j=null;a=V(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.i+=1;return this};function Uc(a,b){U(a);b=V(a,b);a.h.has(b)&&(a.j=null,a.i-=a.h.get(b).length,a.h.delete(b))}function Vc(a,b){U(a);b=V(a,b);return a.h.has(b)}
n.forEach=function(a,b){U(this);this.h.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};function Wc(a,b){U(a);var c=[];if(typeof b==="string")Vc(a,b)&&(c=c.concat(a.h.get(V(a,b))));else for(a=Array.from(a.h.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c}n.set=function(a,b){U(this);this.j=null;a=V(this,a);Vc(this,a)&&(this.i-=this.h.get(a).length);this.h.set(a,[b]);this.i+=1;return this};
n.get=function(a,b){if(!a)return b;a=Wc(this,a);return a.length>0?String(a[0]):b};n.toString=function(){if(this.j)return this.j;if(!this.h)return"";for(var a=[],b=Array.from(this.h.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Wc(this,d);for(var f=0;f<d.length;f++){var g=e;d[f]!==""&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.j=a.join("&")};function Ic(a){var b=new Kc;b.j=a.j;a.h&&(b.h=new Map(a.h),b.i=a.i);return b}
function V(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b}function Qc(a,b){b&&!a.l&&(U(a),a.j=null,a.h.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Uc(this,d),Uc(this,e),c.length>0&&(this.j=null,this.h.set(V(this,e),Aa(c)),this.i+=c.length))},a));a.l=b};function Xc(){var a=Yc();a=Zc(a)!="Chrome"?null:(a=a.match(/\sChrome\/(\d+)/i))&&a.length==2?parseInt(a[1],10):null;return a&&a<30?!1:!db||!pb||pb>9}function $c(a,b){var c=T(b);b=c.j;c=c.h;for(var d=0;d<a.length;d++){var e=a[d];e.indexOf("chrome-extension://")==0?e=T(e).h==c&&b=="chrome-extension":b!="http"&&b!="https"?e=!1:ad.test(e)?e=c==e:(e=e.split(".").join("\\."),e=(new RegExp("^(.+\\."+e+"|"+e+")$","i")).test(c));if(e)return!0}return!1}var ad=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;
function bd(){var a=null;return rc(new O(function(b){x.document.readyState=="complete"?b():(a=function(){b()},Lb(window,"load",a))}),function(b){Ub(window,"load",a);throw b;})}function cd(){return typeof x.WorkerGlobalScope!=="undefined"&&typeof x.importScripts==="function"}function dd(){return firebase.INTERNAL.hasOwnProperty("reactNative")?"ReactNative":firebase.INTERNAL.hasOwnProperty("node")?"Node":cd()?"Worker":"Browser"}
function Zc(a){var b=a.toLowerCase();if(F(b,"opera/")||F(b,"opr/")||F(b,"opios/"))return"Opera";if(F(b,"iemobile"))return"IEMobile";if(F(b,"msie")||F(b,"trident/"))return"IE";if(F(b,"edge/"))return"Edge";if(F(b,"firefox/"))return"Firefox";if(F(b,"silk/"))return"Silk";if(F(b,"blackberry"))return"Blackberry";if(F(b,"webos"))return"Webos";if(!F(b,"safari/")||F(b,"chrome/")||F(b,"crios/")||F(b,"android"))if(!F(b,"chrome/")&&!F(b,"crios/")||F(b,"edge/")){if(F(b,"android"))return"Android";if((a=a.match(RegExp("([a-zA-Z\\d\\.]+)/[a-zA-Z\\d\\.]*$")))&&
a.length==2)return a[1]}else return"Chrome";else return"Safari";return"Other"}function Yc(){return x.navigator&&x.navigator.userAgent||""}function ed(){return x.location&&x.location.protocol||null}function fd(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&a[c]!==null&&a[c]!==void 0&&(b[c]=a[c]);return b}
function gd(){var a=Yc(),b=dd();a=(a||Yc()).toLowerCase();this.h=(a.match(/android/)||a.match(/webos/)||a.match(/iphone|ipad|ipod/)||a.match(/blackberry/)||a.match(/windows phone/)||a.match(/iemobile/)?!0:!1)||b==="ReactNative"}gd.prototype.get=function(){var a=x.navigator;return!a||typeof a.onLine!=="boolean"||ed()!=="http:"&&ed()!=="https:"&&ed()!=="chrome-extension:"&&typeof a.connection==="undefined"||a.onLine?this.h?6E4:3E4:5E3};
function hd(a){typeof console!=="undefined"&&typeof console.error==="function"&&console.error(a)};var id;try{var jd={};Object.defineProperty(jd,"abcd",{configurable:!0,enumerable:!0,value:1});Object.defineProperty(jd,"abcd",{configurable:!0,enumerable:!0,value:2});id=jd.abcd==2}catch(a){id=!1}function W(a,b,c){id?Object.defineProperty(a,b,{configurable:!0,enumerable:!0,value:c}):a[b]=c}function X(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&W(a,c,b[c])}
function kd(a,b){if(!b||!b.length)return!0;if(!a)return!1;for(var c=0;c<b.length;c++){var d=a[b[c]];if(d===void 0||d===null||d==="")return!1}return!0};function ld(){};var md;function nd(){}B(nd,ld);nd.prototype.h=function(){return new XMLHttpRequest};md=new nd;function od(){}B(od,ld);od.prototype.h=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if(typeof XDomainRequest!="undefined")return new pd;throw Error("Unsupported browser");};function pd(){this.h=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText=this.response="";this.status=-1;this.statusText="";this.h.onload=A(this.ea,this);this.h.onerror=A(this.V,this);this.h.onprogress=A(this.fa,this);this.h.ontimeout=A(this.ja,this)}
n=pd.prototype;n.open=function(a,b,c){if(c!=null&&!c)throw Error("Only async requests are supported.");this.h.open(a,b)};n.send=function(a){if(a)if(typeof a=="string")this.h.send(a);else throw Error("Only string data is supported");else this.h.send()};n.abort=function(){this.h.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return a.toLowerCase()=="content-type"?this.h.contentType:""};
n.ea=function(){this.status=200;this.response=this.responseText=this.h.responseText;qd(this,4)};n.V=function(){this.status=500;this.response=this.responseText="";qd(this,4)};n.ja=function(){this.V()};n.fa=function(){this.status=200;qd(this,1)};function qd(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.h.contentType};function rd(a){R.call(this);this.headers=new Map;this.J=a||null;this.i=!1;this.h=null;this.D="";this.l=this.C=this.m=this.B=!1;this.v=0;this.o=null;this.F="";this.H=!1}B(rd,R);var sd=/^https?$/i,td=["POST","PUT"];
function ud(a,b,c,d,e){if(a.h)throw Error("[goog.net.XhrIo] Object is active with another request="+a.D+"; newUri="+b);if(typeof c==="string")var f=c;else if(c){var g=c;f=g.method;d!=null||(d=g.body);e!=null||(e=g.headers)}f=f?f.toUpperCase():"GET";a.D=b;a.B=!1;a.i=!0;a.h=a.J?a.J.h(g):md.h();a.h.onreadystatechange=N(A(a.W,a));try{a.C=!0,a.h.open(f,String(b),!0),a.C=!1}catch(y){wd(a);return}b=d||"";c=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var h in e)c.set(h,e[h]);
else if(typeof e.keys==="function"&&typeof e.get==="function"){h=u(e.keys());d=h.next();var k;try{for(;!d.done;d=h.next()){var l=d.value;c.set(l,e.get(l))}}finally{d&&!d.done&&(k=h.return)&&k.call(h)}}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(c.keys()).find(function(y){return"content-type"==y.toLowerCase()});k=x.FormData&&b instanceof x.FormData;!(xa(td,f)>=0)||e||k||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");f=u(c);e=f.next();var m;
try{for(;!e.done;e=f.next()){var v=u(e.value),q=v.next().value,t=v.next().value;a.h.setRequestHeader(q,t)}}finally{e&&!e.done&&(m=f.return)&&m.call(f)}a.F&&(a.h.responseType=a.F);"withCredentials"in a.h&&a.h.withCredentials!==a.H&&(a.h.withCredentials=a.H);try{xd(a),a.v>0&&(a.o=setTimeout(a.R.bind(a),a.v)),a.m=!0,a.h.send(b),a.m=!1}catch(y){wd(a)}}n=rd.prototype;n.R=function(){typeof ra!="undefined"&&this.h&&(this.dispatchEvent("timeout"),this.abort(8))};
function wd(a){a.i=!1;a.h&&(a.l=!0,a.h.abort(),a.l=!1);yd(a);zd(a)}function yd(a){a.B||(a.B=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}n.abort=function(){this.h&&this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),zd(this))};n.K=function(){this.h&&(this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1),zd(this,!0));rd.M.K.call(this)};n.W=function(){this.isDisposed()||(this.C||this.m||this.l?Ad(this):this.ma())};n.ma=function(){Ad(this)};
function Ad(a){if(a.i&&typeof ra!="undefined")if(a.m&&(a.h?a.h.readyState:0)==4)setTimeout(a.W.bind(a),0);else if(a.dispatchEvent("readystatechange"),(a.h?a.h.readyState:0)==4){a.i=!1;try{var b=Bd(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var f=String(a.D).match(Dc)[1]||null;!f&&x.self&&x.self.location&&(f=x.self.location.protocol.slice(0,-1));e=!sd.test(f?f.toLowerCase():"")}d=e}d?(a.dispatchEvent("complete"),
a.dispatchEvent("success")):yd(a)}finally{zd(a)}}}function zd(a,b){if(a.h){xd(a);var c=a.h;a.h=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=null}catch(d){}}}function xd(a){a.o&&(clearTimeout(a.o),a.o=null)}n.isActive=function(){return!!this.h};function Bd(a){try{return(a.h?a.h.readyState:0)>2?a.h.status:-1}catch(b){return-1}}function Cd(a){try{return a.h?a.h.responseText:""}catch(b){return""}}
n.getResponse=function(){try{if(!this.h)return null;if("response"in this.h)return this.h.response;switch(this.F){case "":case "text":return this.h.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.h)return this.h.mozResponseArrayBuffer}return null}catch(a){return null}};function Dd(){this.h=new od}
function Ed(){var a=new rd((new Dd).h),b={"Content-type":"application/json"};return new O(function(c,d){try{a.v=1E4;var e=setTimeout(function(){a.dispatchEvent("timeout")},1E4);Nb(a,"complete",function(){e&&clearTimeout(e);var f=null,g=Cd(a);if(Bd(a)===200)try{f=JSON.parse(g)||null,c(f||null)}catch(h){d(Error(g))}else Bd(a)===404?d(Error("resource-not-found")):d(Error(g))});Tb(a,"ready",function(){e&&clearTimeout(e);a.dispose()});Tb(a,"timeout",function(){e&&clearTimeout(e);a.dispose();d(Error("Request timed out"))});
ud(a,"/__/firebase/init.json","GET",null,b)}catch(f){d(f)}})};var Fd="oauth_consumer_key oauth_nonce oauth_signature oauth_signature_method oauth_timestamp oauth_token oauth_version".split(" "),Gd=["client_id","response_type","scope","redirect_uri","state"];function Hd(a){X(this,{providerId:a,isOAuthProvider:!0})}function Y(a){Hd.call(this,a,Gd);this.h=[]}B(Y,Hd);function Id(){Y.call(this,"facebook.com")}B(Id,Y);W(Id,"PROVIDER_ID","facebook.com");W(Id,"FACEBOOK_SIGN_IN_METHOD","facebook.com");function Jd(){Y.call(this,"github.com")}B(Jd,Y);W(Jd,"PROVIDER_ID","github.com");W(Jd,"GITHUB_SIGN_IN_METHOD","github.com");function Kd(){Y.call(this,"google.com");xa(this.h,"profile")>=0||this.h.push("profile")}B(Kd,Y);W(Kd,"PROVIDER_ID","google.com");
W(Kd,"GOOGLE_SIGN_IN_METHOD","google.com");function Ld(){Hd.call(this,"twitter.com",Fd)}B(Ld,Hd);W(Ld,"PROVIDER_ID","twitter.com");W(Ld,"TWITTER_SIGN_IN_METHOD","twitter.com");function Md(){X(this,{providerId:"password",isOAuthProvider:!1})}X(Md,{PROVIDER_ID:"password"});X(Md,{EMAIL_LINK_SIGN_IN_METHOD:"emailLink"});X(Md,{EMAIL_PASSWORD_SIGN_IN_METHOD:"password"});
function Nd(a){try{a||firebase.auth()}catch(b){throw new C("argument-error","Either an instance of firebase.auth.Auth must be passed as an argument to the firebase.auth.PhoneAuthProvider constructor, or the default firebase App instance must be initialized via firebase.initializeApp().");}X(this,{providerId:"phone",isOAuthProvider:!1})}X(Nd,{PROVIDER_ID:"phone"});X(Nd,{PHONE_SIGN_IN_METHOD:"phone"});var Od={};function Pd(){throw Error("Do not instantiate directly");}Pd.prototype.U=null;Pd.prototype.toString=function(){return this.content};Pd.prototype.Z=function(){if(this.h!==Od)throw Error("Sanitized content was not of kind HTML.");return Oa(this.toString())};function Qd(){Pd.call(this)}B(Qd,Pd);Qd.prototype.h=Od;function Rd(a){if(a!=null)switch(a.U){case 1:return 1;case -1:return-1;case 0:return 0}return null}var Sd=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));d!==void 0&&(c.U=d);return c}}(Qd);function Td(){return Ud(function(){return""}).replace(Vd,"&lt;")}var Wd=RegExp.prototype.hasOwnProperty("sticky"),Xd=new RegExp((Wd?"":"^")+"(?:!|/?([a-zA-Z][a-zA-Z0-9:-]*))",Wd?"gy":"g");
function Ud(a){for(var b=String("firebase-container".content),c=[],d=b.length,e=0,f=[],g,h,k=0;k<d;){switch(e){case 0:var l=b.indexOf("<",k);if(l<0){if(c.length===0)return b;c.push(b.substring(k));k=d}else c.push(b.substring(k,l)),h=l,k=l+1,Wd?(Xd.lastIndex=k,l=Xd.exec(b)):(Xd.lastIndex=0,l=Xd.exec(b.substring(k))),l?(f=["<",l[0]],g=l[1],e=1,k+=l[0].length):c.push("<");break;case 1:l=b.charAt(k++);switch(l){case "'":case '"':var m=b.indexOf(l,k);m<0?k=d:(f.push(l,b.substring(k,m+1)),k=m+1);break;
case ">":f.push(l);c.push(a(f.join(""),g));e=0;f=[];h=g=null;break;default:f.push(l)}break;default:throw Error();}e===1&&k>=d&&(k=h+1,c.push("<"),e=0,f=[],h=g=null)}return c.join("")}var Yd={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\v":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Zd(a){return Yd[a]}
var $d=/[\x00\x22\x26\x27\x3c\x3e]/g,ae=/[\x00\x22\x27\x3c\x3e]/g,Vd=/</g;/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var be=Symbol("templateFragment"),ce={};function de(a){a=a.errorMessage;if("firebase-container".h===Od){var b=Td();b=String(b).replace(ae,Zd)}else b="firebase-container".replace($d,Zd);return Sd('<div id="error-screen" class="'+b+'">'+(a!=null&&a.h===Od?a:a instanceof I?Sd(Pa(a).toString()):Sd(String(String(a)).replace($d,Zd),Rd(a)))+"</div>")};function ee(a,b){this.j=a;this.i=b;this.h=null}
ee.prototype.render=function(a){var b=b===void 0?!1:b;a:{var c=(0,this.j)(this.i||ce,void 0),d=b;d=d===void 0?!1:d;var e=wa||(wa=new wb);b=c&&c.na?c.na():null;if(!b){b:if(z(c)){if(c.Z){var f=c.Z();if(f instanceof I)break b}f=qb("zSoyz")}else f=qb(String(c));if(d){var g,h;d=(h=(g=e.h)[be])!=null?h:g[be]=yb(e,"TEMPLATE");d.innerHTML=Pa(f);f=d.content;d.textContent="";f=f.childNodes}else b=yb(e,"DIV"),b.innerHTML=Pa(f),f=b.childNodes}if(f.length==1&&(g=f[0],g.nodeType==1)){b=g;break a}if(!b){b=yb(e,
"DIV");e=b.append;g=e.apply;h=b;if(!(f instanceof Array)){f=u(f);for(c=[];!(d=f.next()).done;)c.push(d.value);f=c}g.call(e,h,f)}}this.h=b;a.appendChild(this.h)};ee.prototype.dispose=function(){if(this.h){var a=this.h;a&&a.parentNode&&a.parentNode.removeChild(a);this.h=null}};function fe(a){ee.call(this,de,{errorMessage:a})}ja(fe,ee);function ge(a){this.l=a.pa||null;this.i=a.xa||!1;this.j=a.ya||!1;if(this.i&&this.j)throw Error();}B(ge,ld);ge.prototype.h=function(a){var b=new he(this.l,this.i,this.j);a&&(b.i=a);return b};
function he(a,b,c){R.call(this);this.aa=a;this.o=b;this.C=c||!1;this.B=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.F=new Headers;this.l=null;this.J="GET";this.S="";this.h=!1;this.H=this.m=this.v=null;this.D=new AbortController;this.i=void 0}B(he,R);n=he.prototype;n.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.J=a;this.S=b;this.readyState=1;ie(this)};
n.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");var b,c=((b=this.i)==null?0:b.signal)?AbortSignal.any([this.i.signal,this.D.signal]):this.D.signal;if(c.aborted)throw this.abort(),Error("Request was aborted.");this.h=!0;var d,e,f,g;b=Object.assign({},this.i,{headers:this.F,method:this.J,credentials:(f=(d=this.i)==null?void 0:d.credentials)!=null?f:this.B,cache:(g=(e=this.i)==null?void 0:e.cache)!=null?g:void 0,signal:c});a&&(b.body=a);(this.aa||x).fetch(new Request(this.S,
b)).then(this.ia.bind(this),this.P.bind(this))};n.abort=function(){this.response=this.o||this.C?[]:"";this.responseText="";this.F=new Headers;this.status=0;this.D.abort("Request was aborted.");this.m&&this.m.cancel("Request was aborted.").catch(function(){});this.readyState>=1&&this.h&&this.readyState!=4&&(this.h=!1,je(this));this.readyState=0};
n.ia=function(a){if(this.h&&(this.v=a,this.l||(this.status=this.v.status,this.statusText=this.v.statusText,this.l=a.headers,this.readyState=2,ie(this)),this.h&&(this.readyState=3,ie(this),this.h)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.ga.bind(this),this.P.bind(this));else if(a.body&&x.ReadableStream){this.m=a.body.getReader();if(this.o||this.C){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" or "streamTextChunks" mode responses.');this.response=
[]}else this.response=this.responseText="";this.o||(this.H=new TextDecoder);ke(this)}else a.text().then(this.ha.bind(this),this.P.bind(this))};function ke(a){a.m.read().then(a.da.bind(a)).catch(a.P.bind(a))}n.da=function(a){if(this.h){var b=a.value;if(this.o)a.value&&this.response.push(b||new Uint8Array(0));else if(b=b?this.H.decode(b,{stream:!a.done}):"")this.C?this.response.push(b):this.response=this.responseText+=b;a.done?je(this):ie(this);this.readyState==3&&ke(this)}};
n.ha=function(a){this.h&&(this.response=this.responseText=a,je(this))};n.ga=function(a){this.h&&(this.response=a,je(this))};n.P=function(){this.h&&je(this)};function je(a){a.readyState=4;a.v=null;a.m=null;a.H=null;ie(a)}n.setRequestHeader=function(a,b){this.F.append(a,b)};n.getResponseHeader=function(a){return this.l?this.l.get(a.toLowerCase())||"":""};
n.getAllResponseHeaders=function(){if(!this.l)return"";for(var a=[],b=this.l.entries(),c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function ie(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(he.prototype,"withCredentials",{get:function(){return this.B==="include"},set:function(a){this.B=a?"include":"same-origin"}});/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function Z(a){var b=le;this.m=[];this.D=b;this.C=a||null;this.l=this.j=!1;this.i=void 0;this.A=this.I=this.o=!1;this.u=0;this.h=null;this.v=0}Z.prototype.cancel=function(a){if(this.j)this.i instanceof Z&&this.i.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.v--,b.v<=0&&b.cancel())}this.D?this.D.call(this.C,this):this.A=!0;this.j||(a=new me(this),ne(this),oe(this,!1,a))}};Z.prototype.B=function(a,b){this.o=!1;oe(this,a,b)};function oe(a,b,c){a.j=!0;a.i=c;a.l=!b;pe(a)}
function ne(a){if(a.j){if(!a.A)throw new qe(a);a.A=!1}}function re(a,b){se(a,null,b)}function se(a,b,c,d){var e=a.j;e||(b===c?b=c=N(b):(b=N(b),c=N(c)));a.m.push([b,c,d]);e&&pe(a)}Z.prototype.then=function(a,b,c){var d,e,f=new O(function(g,h){e=g;d=h});se(this,e,function(g){g instanceof me?f.cancel():d(g);return te},this);return f.then(a,b,c)};Z.prototype.$goog_Thenable=!0;function ue(a){return za(a.m,function(b){return typeof b[1]==="function"})}var te={};
function pe(a){if(a.u&&a.j&&ue(a)){var b=a.u,c=ve[b];c&&(x.clearTimeout(c.h),delete ve[b]);a.u=0}a.h&&(a.h.v--,delete a.h);b=a.i;for(var d=c=!1;a.m.length&&!a.o;){var e=a.m.shift(),f=e[0],g=e[1];e=e[2];if(f=a.l?g:f)try{var h=f.call(e||a.C,b);h===te&&(h=void 0);h!==void 0&&(a.l=a.l&&(h==b||h instanceof Error),a.i=b=h);if(lc(b)||typeof x.Promise==="function"&&b instanceof x.Promise)d=!0,a.o=!0}catch(k){b=k,a.l=!0,ue(a)||(c=!0)}}a.i=b;d&&(h=A(a.B,a,!0),d=A(a.B,a,!1),b instanceof Z?(se(b,h,d),b.I=!0):
b.then(h,d));c&&(b=new we(b),ve[b.h]=b,a.u=b.h)}function qe(){D.call(this)}B(qe,D);qe.prototype.message="Deferred has already fired";qe.prototype.name="AlreadyCalledError";function me(){D.call(this)}B(me,D);me.prototype.message="Deferred was canceled";me.prototype.name="CanceledError";function we(a){this.h=x.setTimeout(A(this.j,this),0);this.i=a}we.prototype.j=function(){delete ve[this.h];throw this.i;};var ve={};function xe(a){var b={},c=b.document||document,d=Ka(a).toString(),e=yb(new wb(c),"SCRIPT"),f={Y:e,R:void 0},g=new Z(f),h=null,k=b.timeout!=null?b.timeout:5E3;k>0&&(h=window.setTimeout(function(){ye(e,!0);var l=new ze(1,"Timeout reached for loading script "+d);ne(g);oe(g,!1,l)},k),f.R=h);e.onload=e.onreadystatechange=function(){e.readyState&&e.readyState!="loaded"&&e.readyState!="complete"||(ye(e,b.ra||!1,h),ne(g),oe(g,!0,null))};e.onerror=function(){ye(e,!0,h);var l=new ze(0,"Error while loading script "+
d);ne(g);oe(g,!1,l)};f=b.attributes||{};Da(f,{type:"text/javascript",charset:"UTF-8"});sb(e,f);Ra(e,a);Ae(c).appendChild(e);return g}function Ae(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&b.length!==0?b[0]:a.documentElement}function le(){if(this&&this.Y){var a=this.Y;a&&a.tagName=="SCRIPT"&&ye(a,!0,this.R)}}
function ye(a,b,c){c!=null&&x.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function ze(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);D.call(this,c);this.code=a}B(ze,D);var Be=la(["https://apis.google.com/js/client.js?onload=",""]);function Ce(a){this.i=a}ja(Ce,ld);Ce.prototype.h=function(){return new this.i};
function De(a){this.i=a;var b=b||{};this.l=b.firebaseEndpoint||"https://www.googleapis.com/identitytoolkit/v3/relyingparty/";this.o=b.identityPlatformEndpoint||"https://identitytoolkit.googleapis.com/v2/";this.u=b.firebaseTimeout||Ee;a=b.firebaseHeaders||Fe;b={};for(var c in a)b[c]=a[c];this.m=b;c=dd()=="Node";c=x.XMLHttpRequest||c&&firebase.INTERNAL.node&&firebase.INTERNAL.node.XMLHttpRequest;if(!c&&!cd())throw new C("internal-error","The XMLHttpRequest compatibility library was not found.");this.h=
void 0;cd()?this.h=new ge({pa:self}):(a=dd(),a==="ReactNative"||a==="Node"?this.h=new Ce(c):this.h=new od);this.j=null}var Ge;function He(a,b,c,d,e,f,g){Xc()||cd()?a=A(a.A,a):(Ge||(Ge=new O(function(h,k){Ie(h,k)})),a=A(a.v,a));a(b,c,d,e,f,g)}
De.prototype.A=function(a,b,c,d,e,f){if(cd()&&(typeof x.fetch==="undefined"||typeof x.Headers==="undefined"||typeof x.Request==="undefined"))throw new C("operation-not-supported-in-this-environment","fetch, Headers and Request native APIs or equivalent Polyfills must be available to support HTTP requests from a Worker environment.");var g=new rd(this.h);if(f){g.v=Math.max(0,f);var h=setTimeout(function(){g.dispatchEvent("timeout")},f)}Nb(g,"complete",function(){h&&clearTimeout(h);var k=null;try{k=
JSON.parse(Cd(this))||null}catch(l){k=null}b&&b(k)});Tb(g,"ready",function(){h&&clearTimeout(h);this.dispose()});Tb(g,"timeout",function(){h&&clearTimeout(h);this.dispose();b&&b(null)});ud(g,a,c,d,e)};function Ie(a,b){if(((window.gapi||{}).client||{}).request)a();else{x[Je]=function(){((window.gapi||{}).client||{}).request?a():b(Error("CORS_UNSUPPORTED"))};var c=rb(Be,Je);re(xe(c),function(){b(Error("CORS_UNSUPPORTED"))})}}
De.prototype.v=function(a,b,c,d,e){var f=this;rc(Ge.then(function(){window.gapi.client.setApiKey(f.i);var g=window.gapi.auth.getToken();window.gapi.auth.setToken(null);window.gapi.client.request({path:a,method:c,body:d,headers:e,authType:"none",callback:function(h){window.gapi.auth.setToken(g);b&&b(h)}})}),function(g){b&&b({error:{message:g&&g.message||"CORS_UNSUPPORTED"}})})};
function Ke(a,b,c,d,e,f,g){var h=T(b+c);h.i.set("key",a.i);g&&h.i.set("cb",Date.now().toString());var k=d=="GET";if(k)for(var l in e)e.hasOwnProperty(l)&&h.i.set(l,e[l]);return new O(function(m,v){He(a,h.toString(),function(q){if(q)if(q.error){a:{var t=f||{};var y=(q.error&&q.error.errors&&q.error.errors[0]||{}).reason||"";var E={keyInvalid:"invalid-api-key",ipRefererBlocked:"app-not-authorized"};if(y=E[y]?new C(E[y]):null)q=y;else{y=q.error&&(q.error.reason||q.error.message)||"";E={INVALID_CUSTOM_TOKEN:"invalid-custom-token",
CREDENTIAL_MISMATCH:"custom-token-mismatch",MISSING_CUSTOM_TOKEN:"internal-error",INVALID_IDENTIFIER:"invalid-email",MISSING_CONTINUE_URI:"internal-error",INVALID_EMAIL:"invalid-email",INVALID_PASSWORD:"wrong-password",USER_DISABLED:"user-disabled",MISSING_PASSWORD:"internal-error",EMAIL_EXISTS:"email-already-in-use",PASSWORD_LOGIN_DISABLED:"operation-not-allowed",INVALID_IDP_RESPONSE:"invalid-credential",INVALID_PENDING_TOKEN:"invalid-credential",FEDERATED_USER_ID_ALREADY_LINKED:"credential-already-in-use",
MISSING_OR_INVALID_NONCE:"missing-or-invalid-nonce",INVALID_MESSAGE_PAYLOAD:"invalid-message-payload",INVALID_RECIPIENT_EMAIL:"invalid-recipient-email",INVALID_SENDER:"invalid-sender",EMAIL_NOT_FOUND:"user-not-found",RESET_PASSWORD_EXCEED_LIMIT:"too-many-requests",EXPIRED_OOB_CODE:"expired-action-code",INVALID_OOB_CODE:"invalid-action-code",MISSING_OOB_CODE:"internal-error",INVALID_PROVIDER_ID:"invalid-provider-id",CREDENTIAL_TOO_OLD_LOGIN_AGAIN:"requires-recent-login",INVALID_ID_TOKEN:"invalid-user-token",
TOKEN_EXPIRED:"user-token-expired",USER_NOT_FOUND:"user-token-expired",CORS_UNSUPPORTED:"cors-unsupported",DYNAMIC_LINK_NOT_ACTIVATED:"dynamic-link-not-activated",INVALID_APP_ID:"invalid-app-id",TOO_MANY_ATTEMPTS_TRY_LATER:"too-many-requests",WEAK_PASSWORD:"weak-password",PASSWORD_DOES_NOT_MEET_REQUIREMENTS:"password-does-not-meet-requirements",OPERATION_NOT_ALLOWED:"operation-not-allowed",USER_CANCELLED:"user-cancelled",CAPTCHA_CHECK_FAILED:"captcha-check-failed",INVALID_APP_CREDENTIAL:"invalid-app-credential",
INVALID_CODE:"invalid-verification-code",INVALID_PHONE_NUMBER:"invalid-phone-number",INVALID_SESSION_INFO:"invalid-verification-id",INVALID_TEMPORARY_PROOF:"invalid-credential",INVALID_TENANT_ID:"invalid-tenant-id",MISSING_APP_CREDENTIAL:"missing-app-credential",MISSING_CODE:"missing-verification-code",MISSING_PHONE_NUMBER:"missing-phone-number",MISSING_SESSION_INFO:"missing-verification-id",QUOTA_EXCEEDED:"quota-exceeded",SESSION_EXPIRED:"code-expired",REJECTED_CREDENTIAL:"rejected-credential",INVALID_CONTINUE_URI:"invalid-continue-uri",
MISSING_ANDROID_PACKAGE_NAME:"missing-android-pkg-name",MISSING_IOS_BUNDLE_ID:"missing-ios-bundle-id",UNAUTHORIZED_DOMAIN:"unauthorized-continue-uri",INVALID_DYNAMIC_LINK_DOMAIN:"invalid-dynamic-link-domain",INVALID_OAUTH_CLIENT_ID:"invalid-oauth-client-id",INVALID_CERT_HASH:"invalid-cert-hash",UNSUPPORTED_TENANT_OPERATION:"unsupported-tenant-operation",TENANT_ID_MISMATCH:"tenant-id-mismatch",ADMIN_ONLY_OPERATION:"admin-restricted-operation",INVALID_MFA_PENDING_CREDENTIAL:"invalid-multi-factor-session",
MFA_ENROLLMENT_NOT_FOUND:"multi-factor-info-not-found",MISSING_MFA_PENDING_CREDENTIAL:"missing-multi-factor-session",MISSING_MFA_ENROLLMENT_ID:"missing-multi-factor-info",EMAIL_CHANGE_NEEDS_VERIFICATION:"email-change-needs-verification",SECOND_FACTOR_EXISTS:"second-factor-already-in-use",SECOND_FACTOR_LIMIT_EXCEEDED:"maximum-second-factor-count-exceeded",UNSUPPORTED_FIRST_FACTOR:"unsupported-first-factor",UNVERIFIED_EMAIL:"unverified-email",API_KEY_SERVICE_BLOCKED:"api-key-service-blocked"};t=t||
{};Da(E,t);t=(t=y.match(/^[^\s]+\s*:\s*([\s\S]*)$/))&&t.length>1?t[1]:void 0;for(var vd in E)if(y.indexOf(vd)===0){q=new C(E[vd],t);break a}!t&&q&&(t=typeof q==="undefined"?null:JSON.stringify(q));q=new C("internal-error",t)}}v(q)}else m(q);else v(new C("network-request-failed"))},d,k?void 0:JSON.stringify(fd(e)),a.m,a.u.get())})}function Le(a){return Me(a).then(function(b){return b.authorizedDomains||[]})}function Ne(a){return Me(a).then(function(b){return b.projectId||""})}
function Me(a){var b=Oe,c={};if(!kd(c,b.sa))return pc();var d=!!b.za,e=b.ka||"POST",f;return Q(c).then(b.ta).then(function(){b.wa&&(c.returnSecureToken=!0);b.ua&&a.j&&typeof c.tenantId==="undefined"&&(c.tenantId=a.j);return d?Ke(a,a.o,b.endpoint,e,c,b.ca,b.T||!1):Ke(a,a.l,b.endpoint,e,c,b.ca,b.T||!1)}).then(function(g){f=g;return b.oa?b.oa(c,f):f}).then(b.va).then(function(){if(!b.X)return f;if(!(b.X in f))throw new C("internal-error");return f[b.X]})}new gd;
var Ee=new gd,Fe={"Content-Type":"application/json"},Je="__fcb"+Math.floor(Math.random()*1E6).toString(),Oe={T:!0,endpoint:"getProjectConfig",ka:"GET"};function Pe(){var a=Qe,b=wa||(wa=new wb),c=xb(b,"HEAD")[0];if(!c){var d=xb(b,"BODY")[0];c=b.i("HEAD");d.parentNode.insertBefore(c,d)}d=b.i("STYLE");var e=Qa("style",document);e&&d.setAttribute("nonce",e);a=Ta(a);if(x.trustedTypes)if("textContent"in d)d.textContent=a;else if(d.nodeType==3)d.data=String(a);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=String(a)}else{for(;e=d.firstChild;)d.removeChild(e);d.appendChild((d.nodeType==
9?d:d.ownerDocument||d.document).createTextNode(String(a)))}else d.innerHTML=a;b.j(c,d)};var Re=la(["body{margin:0}.firebase-container{background-color:#fff;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;color:rgba(0,0,0,.87);direction:ltr;font:16px Roboto,arial,sans-serif;margin:0 auto;max-width:360px;overflow:hidden;padding-top:8px;position:relative;width:100%}@media (max-width:520px){.firebase-container{box-shadow:none;max-width:none;width:100%}}"]),Qe=function(a){for(var b=oa.apply(1,arguments),c="",d=0;d<a.length;d++)c+=a[d],d<b.length&&(c+=Ta(b[d]));
return new Sa(c)}(Re);x.document.readyState=="complete"?(Pe(),Se()):Lb(window,"load",function(){Pe();Se()});
function Se(){Q().then(function(){var a=Sc(T(x.window&&x.window.location.href||self&&self.location&&self.location.href||""),"link");if(a&&Te(a))return Ue(a).then(function(b){if(b){b=x.window;var c="about:blank";if(a){var d=d===void 0?Na:d;a:if(d=d===void 0?Na:d,a instanceof G)d=a;else{for(c=0;c<d.length;++c){var e=d[c];if(e instanceof Ma&&e.la(a)){d=new G(a);break a}}d=void 0}d=d||La;if(d instanceof G)c=d.h;else throw Error("");}b.location.href=c}else return Ve()},function(){return Ve()});hd("Request is missing required data.");
return Ve()})}
function Ue(a){var b=Sc(T(a),"apiKey"),c=new De(b);return rc(rc(Le(c),function(d){hd("Unable to verify that the app domain is authorized.");throw d;}).then(function(d){return $c(d,a)?Ed().then(function(e){return e.apiKey&&b===e.apiKey?Q(!0):Le(new De(e.apiKey)).then(function(f){if($c(f,a))return Q(!0);hd("App domain is unauthorized in the Firebase Hosting project.");return Q(!1)},function(){return Ne(c).then(function(f){return e.messagingSenderId&&e.messagingSenderId!==f?Q(!1):Q(!0)},function(f){throw f;
})})},function(){return Q(!0)}):(hd("App domain is unauthorized"),Q(!1))}),function(){return Q(!1)})}function Te(a){return a?(a=T(a),!(!(Sc(a,"apiKey")&&Sc(a,"mode")&&Sc(a,"oobCode"))||a.j!="http"&&a.j!="https")):!1}function Ve(){return bd().then(function(){(new fe("The operation is not valid.")).render(document.body)})};
